### ISSUE TITLE
Freifunk-meet not available in brew cask

### ISSUE THREAD

**Issue by simphide** [freifunkMUC/jitsi-meet-electron#12]
When I tried to install the tool via brew cask the following error occurred:

⋊> ~ brew cask install freifunk-meet
Error: Cask 'freifunk-meet' is unavailable: No Cask with this name exists.

**Comment by dpunkturban** [comment]
Looks like it hasn't been merged into the Brew Cask Repo yet.

See: https://github.com/Homebrew/homebrew-cask/pull/84747

**Comment by simphide** [comment]
are you going to open a own tap for freifunk-meet then?

**Comment by awlx** [comment]
My time is limited at the moment. I will try but if someone else wants to do this it's very welcome :).

**Comment by simphide** [comment]
I think this should work https://github.com/freifunkMUC/jitsi-meet-electron/pull/13

**Comment by simphide** [comment]
You can use the following repo - just clone and maintain it:
https://github.com/simphide/homebrew-freifunkmeet

**Comment by awlx** [comment]
Forked your repo and added it to the README. Thank you for your effort!
