### ISSUE TITLE
copy/paste link no longer working

### ISSUE THREAD

**Issue by pdarcos** [freifunkMUC/jitsi-meet-electron#24]
Hi again,

Since I compiled the latest version earlier today everything is working fine except for copy/pasting the meeting link.

Just as before, when you click to share the link it turns green and says link copied.

But then when you go to paste the link the clipboard is empty.

Tested on windows 10 and Macbook pro running Big Sur. Perhaps electron 12 introduced some change?

**Comment by awlx** [comment]
Hm, it's working for me. On Big Sur with an M1 Mac. What exactly doesn't work? Other servers than meet.ffmuc.net?

**Comment by pdarcos** [comment]
Nevermind. I updated to latest version and now all is working fine.
