### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by tubia** [freifunkMUC/jitsi-meet-electron#3]
Hi,
I was happily testing your version of jitsi-meet app since you are making a great job in updating it.

I wanted to give some feedback on my experience.

I have always used in my tests linux mint 19.3.

With a x230 laptop I got on videocalls the 40% less usage of the CPU compared to using the browser.

With a T460s laptop, on videocalls, I got 180% of CPU usage, while disabling the video immediately led to 130% usage (I didn't tested on the browser yet).

Do you have any suggestion on how to better test performances?

**Comment by freechelmi** [comment]
Please check that your GPU allow VP8 coding/decoding with VP8

**Comment by k0a1a** [comment]
does this also require VP8 codec present on the system?

**Comment by freechelmi** [comment]
No , vp8 is included in electron. However I'm not sure if electron has GPU decoding enabled.

On Mint just install and run vainfo http://apt.ubuntu.com/p/vainfo  to know

**Comment by k0a1a** [comment]
Thanks for your reply.

I'd like to provide some more details: a video call with two participants (non p2p) causes about 10% CPU load on i5-8350U CPU (system load ~0.4)

Each new participant joining the call, seems to increase the CPU load by about the 10%. 

Looking  at _top -c_ it appears that '--type=renderer' thread of Electron/Chromium is causing most of the load. 

I'm not familiar enough with Chromium internals to determine if 'renderer' thread isn't making use of H264/VP9 hardware decoding or something else is off. 

According to _vainfo_ hardware decoding is available and a stand-alone instance of Chromium v81 seems to be making use of it, see below:

![Screenshot at 2020-04-10 22-07-01](https://user-images.githubusercontent.com/876449/79020051-1497b500-7b78-11ea-90f0-313197e423d7.png)

![Screenshot at 2020-04-10 22-09-31](https://user-images.githubusercontent.com/876449/79020059-1b262c80-7b78-11ea-8a71-4e78b02ad1ba.png)

Hope this is useful

**Comment by awlx** [comment]
CPU usage should now be reduced on our instance at https://meet.ffmuc.net.

**Comment by beatstick** [comment]
> 
> 
> CPU usage should now be reduced on our instance at https://meet.ffmuc.net.

Could you please provide some information on how to reduce clients CPU usage server side?

**Comment by freechelmi** [comment]
> According to _vainfo_ hardware decoding is available and a stand-alone instance of Chromium v81 seems to be making use of it, see below:

It is not. Default chromium on Mint/ubuntu does not use Gpu Decoding, at least for played video. You would see some at the end of the about:gpu page about it
