### ISSUE TITLE
Desktop sharing: not switching back to camera

### ISSUE THREAD

**Issue by RagingSquirrel** [freifunkMUC/jitsi-meet-electron#4]
Desktop sharing works- After the desktop sharing is finished, the jitsi-meet-electron is not switching back to the camera. Only restarting the jitsi-meet-electron solves the problem.

(Version 2.0.4 on Windows 10)

**Comment by awlx** [comment]
@RagingSquirrel we released a new version can you try if that fixes the issue?

**Comment by RagingSquirrel** [comment]
I have dane a test. Desktop sharing works well now. Many thanks!
