### ISSUE TITLE
pass parameters on start

### ISSUE THREAD

**Issue by erniberni** [freifunkMUC/jitsi-meet-electron#5]
Would it be possible to pass the jitsi server and the conference name as parameters when starting the linux app/program from command line or script?

**Comment by awlx** [comment]
We are merging the protocol handler now:
https://github.com/freifunkMUC/jitsi-meet-electron/commit/4a7581df2f767906a1c7e90f529ed89aa2ef3815

Maybe this offers a way to also do this in the future.

**Comment by awlx** [comment]
This is possible now, just tested with MacOS:
`open FreifunkMeet.app/ jitsi-meet://meet.ffmuc.net/blabla`
