### ISSUE TITLE
Windows-Download-Link 404

### ISSUE THREAD

**Issue by UweKeim** [freifunkMUC/jitsi-meet-electron#57]
The download link on https://github.com/freifunkMUC/jitsi-meet-electron#installation points to https://github.com/freifunkMUC/jitsi-meet-electron/releases/latest/download/ffmuc-meet.exe which results in 404.

Could you please fix the link and/or tell me the correct download URL?

**Comment by GoliathLabs** [comment]
@UweKeim should now be working again 😄
